version: "3"
services:
    web:
        build: ./nginx
        ports:
          - "80:80"
        links:
          - php
        volumes:
          - magento:/var/www/magento
          - magento-vendor:/var/www/magento/vendor
    php:
        build: ./php
        expose:
          - 9000
        volumes:
          - magento:/var/www/magento
          - magento-vendor:/var/www/magento/vendor
        depends_on:
          - db
    db:
        image: mariadb:latest
        expose:
          - 3306
        environment:
          MYSQL_ROOT_PASSWORD: 123123q
          MYSQL_DATABASE: magento
          MYSQL_USER: magento
          MYSQL_PASSWORD: 123123q
volumes:
    magento:
    magento-vendor:
